services:
  - type: web
    name: security-scanner
    env: node
    buildCommand: |
      npm install
      npm run clean
      npm run build:server
      ls -la dist/server
      npm run build:client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_OPTIONS
        value: --experimental-specifier-resolution=node
    healthCheckPath: /
    autoDeploy: true
    plan: free
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - server/**
        - client/**
        - shared/**
        - vite.config.ts
        - tsconfig.json
        - tsconfig.server.json